pipeline:
  identifier: Build_raj470_terraform_aws_awstemplates_1727959695244
  name: Build terraform-aws-awstemplates
  orgIdentifier: default
  projectIdentifier: dev
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1727959663006
        repoName: raj470/terraform-aws-awstemplates
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: setupvirtualenvironment
                  name: setup virtual environment
                  spec:
                    command: |-
                      python3 -m venv .venv
                      . .venv/bin/activate
                      python3 -m pip install -r requirements.txt
                      python3 -m pip install -e .
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
